### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by slamdunk1002** [shuiyihang/trackCar#1]
hello，
    请问我复现后最终结果只有900多，中间最高出现也就1200多，这正常吗？总共训练2000次，是在哪里需要优化吗？

**Comment by shuiyihang** [comment]
你好，因为在step中设置了达到1000时间步，自动终止，为了防止某一轮效果特别好，一直运行，所以最高出现1200是正常的。
if self.step_nums > 1000:

并不需要训练2000次，一般运气好几百次就效果很好了。

**Comment by shuiyihang** [comment]
现在我将关闭这个问题，如果有任何问题，请再打开
